project:
  name: mainstacktesting
  regions:
    - us-east-1

tests:
  MainStackTest:
    template: main.yml
    parameters:
      VPCName: Lab2_Group14
      VPCCIDR: 10.0.0.0/16
      PublicSubnetCIDR: 10.0.0.0/24
      PrivateSubnetCIDR: 10.0.1.0/24
      InternetGateWayName: Lab1_Group14_IGW
      PrivateSubnetName: Lab1_Group14_Private
      PublicSubnetName: Lab1_Group14_Public
      KeyName: Lab1_Group14_Key
      InstanceTypeParameter: t3.micro
      PublicEC2InstanceSecurityGroupName: Lab1_Group14_Public_SG
      PrivateEC2InstanceSecurityGroupName: Lab1_Group14_Private_SG